//
//  SyncMusicViewController.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 03.02.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SyncMusicDisplayLogic: class {
    func displaySomething(viewModel: SyncMusic.Something.ViewModel)
}

final class SyncMusicViewController: UIViewController {
    
    //MARK: Variables
    private var interactor: SyncMusicBusinessLogic?
    
    // MARK: View lifecycle
    override func viewDidLoad() {
        super.viewDidLoad()
        setupCleanCycle()
    }
    
    //MARK: Setup
    private func setupCleanCycle() {
        let viewController = self
        let interactor = SyncMusicInteractor()
        let presenter = SyncMusicPresenter()
        viewController.interactor = interactor
        interactor.presenter = presenter
        presenter.viewController = viewController
    }
}

extension SyncMusicViewController: SyncMusicDisplayLogic {
    func displaySomething(viewModel: SyncMusic.Something.ViewModel) {
    }
}
