//
//  SyncMusicRouter.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 04.02.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

@objc protocol SyncMusicInput {
    func routeToMusicViewController()
}

protocol SyncMusicDataPassing {
    var dataStore: SyncMusicDataStore? { get }
}

final class SyncMusicRouter: NSObject, SyncMusicInput, SyncMusicDataPassing {
    
    weak var viewController: SyncMusicViewController?
    var dataStore: SyncMusicDataStore?
    
    //MARK: Routing
    func routeToMusicViewController() {
        guard let viewController = viewController else { return }
        navigateToMusicViewController(source: viewController)
    }
    
    // MARK: Passing data
    
    // MARK: Navigation
    private func navigateToMusicViewController(source: SyncMusicViewController) {
        source.dismiss(animated: true)
    }
}
