//
//  SyncMusicPresenter.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 03.02.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol SyncMusicPresentationLogic {
    func presentSomething(response: SyncMusic.Something.Response)
}

final class SyncMusicPresenter: SyncMusicPresentationLogic {
    
    weak var viewController: SyncMusicDisplayLogic?
    
    // MARK: Do something
    func presentSomething(response: SyncMusic.Something.Response) {
        let viewModel = SyncMusic.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
