# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'VideoPlayer' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  pod 'MarqueeLabel', '4.0.5'
  pod 'lottie-ios', '3.1.9'

end
