//
//  testPresenter.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 04.02.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol testPresentationLogic {
    func presentSomething(response: test.Something.Response)
}

class testPresenter: testPresentationLogic {
    
    weak var viewController: testDisplayLogic?
    
    // MARK: Do something
    
    func presentSomething(response: test.Something.Response) {
        let viewModel = test.Something.ViewModel()
        viewController?.displaySomething(viewModel: viewModel)
    }
}
