//
//  FetchFromLocalStorageWorker.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 13.01.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FetchFromLocalStorageWorker {
    /**
        Check local storage files by extension, create Core Data objects and replase files from document directory to temp directory.
     */
    func fetch(byTypeExtension itemExtension: String) {
        let musicURLS = FileManager.default.getFilesFromDocumentDirectory(withFileExtension: itemExtension)

        var newObects = [MusicOrVideoItem]()
        
        for itemURL in musicURLS {
            let itemName = itemURL.lastPathComponent
            //TODO: add logic for store UUID in mp3 for easy match
            guard FileManager.default.replaceItemInDocumentFolder(from: itemURL, fileName: itemName) else {
                //TODO: show user error
                continue
            }
            
            let musicItem = MusicOrVideoItem.init(fileName: itemName)
            newObects.append(musicItem)
        }
        CoreManager.shared.saveContext()
        //TODO: add logic for compare local files and count in core data and remove unused from local storage and db
    }
}
