//
//  FetchFromLocalStorageWorker.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 13.01.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

class FetchFromLocalStorageWorker {
    /**
        Check local storage files by extension, create Core Data objects and replase files from document directory to temp directory.
     */
    func fetch(byTypeExtension itemExtension: String) {
        let musicURLS = FileManager.default.getFilesFromDocumentDirectory(withFileExtension: itemExtension)

        var newObects = [MusicOrVideoItem]()
        
        for itemURL in musicURLS {
            let musicItem = MusicOrVideoItem.init(fileName: itemURL.lastPathComponent,
                                                  fileExtension: itemExtension)
            
            let resultOfReplacing = FileManager.default.replaceItemInDocumentFolder(from: itemURL,
                                                                                    fileName: musicItem.fileNameInStorage)
            if !resultOfReplacing {
                //TODO: show user error
                continue
            }
            
            
            newObects.append(musicItem)
        }
        CoreManager.shared.saveContext()
        //TODO: add logic for compare local files and count in core data and remove unused from local storage and db
    }
}
