//
//  MusicModels.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 13.01.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Music {
    // MARK: Use cases
    
    enum FetchLocalItems {
        struct Request {
        }
        
        struct Response {
            var musicItems: [MusicOrVideoItem]
        }
        
        struct ViewModel {
            struct MusicDisplayData {
                var fileName: String
                var isNew: Bool
            }
            
            var musicDisplayDataArray: [MusicDisplayData]
        }
    }
}
