//
//  MusicModels.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 13.01.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

enum Music {
    // MARK: Use cases
    //FIXME: можно ли делать так?
    struct MusicDisplayData {
        var fileName: String
        var isNew: Bool
    }
    
    enum FetchLocalItems {
        struct Request {
        }
        
        struct Response {
            var musicItems: [MusicOrVideoItem]
        }
        
        struct ViewModel {
            var musicDisplayDataArray: [MusicDisplayData]
        }
    }
    
    enum StartPlayOrDownload {
        struct Request {
            let index: Int
        }
        
        struct Response {
            var musicItem: MusicOrVideoItem
            var atIndex: Int
        }
        
        struct ViewModel {
            var musicItem: MusicDisplayData
            var atIndex: Int
        }
    }
    
    enum UpdatePlayingSongInfo {
        struct Request {
        }
        
        struct Response {
            var info: [String: Any]
        }
        
        struct ViewModel {
            var info: [String: Any]
        }
    }
}
