//
//  MusicInteractor.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 13.01.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MusicBusinessLogic {
    func fetchLocalItems(request: Music.FetchLocalItems.Request)
    func startPlayOrDownload(request: Music.StartPlayOrDownload.Request)
    func updatePlayingSongInfo(request: Music.UpdatePlayingSongInfo.Request)
}

class MusicInteractor: MusicBusinessLogic {
    
    var presenter: MusicPresentationLogic?
    //workerks
    private var fetchWorker: FetchFromLocalStorageWorker?
    private var playWorker: PlayMusicWorker?
    
    //business logic variables
    private(set) var itemsSet = Set<MusicOrVideoItem>()
    private(set) var itemsArray = [MusicOrVideoItem]()
    private var indexOfItemForPlay = 0
    
    private let musicExtension = ".mp3"
    
    // MARK: Do something
    func fetchLocalItems(request: Music.FetchLocalItems.Request) {
        fetchWorker = FetchFromLocalStorageWorker()
        fetchWorker?.fetch(byTypeExtension: musicExtension)
        
        itemsSet = CoreManager.shared.getMediaItems()
        itemsArray = Array(itemsSet)
        
        let response = Music.FetchLocalItems.Response(musicItems: itemsArray)
        presenter?.showMusicItems(response: response)
    }
    
    func startPlayOrDownload(request: Music.StartPlayOrDownload.Request) {
        indexOfItemForPlay = request.index
        
        guard   !itemsArray.isEmpty,
                indexOfItemForPlay >= 0,
                indexOfItemForPlay < itemsArray.count
        else {return}
        
        let itemForPlay = itemsArray[indexOfItemForPlay]
        
        let fileUrl = FileManager.default.applicationSupportDirectory.appendingPathComponent(itemForPlay.fileNameInStorage,
                                                                                   isDirectory: false)
        guard FileManager.default.fileExists(atPath: fileUrl.path) else {
            //TODO: here should call worker which download items from cloud
            print("❌ file not found on device")
            return
        }
        
        if itemForPlay.isNew {
            itemsArray[indexOfItemForPlay].isNew = false
            saveChanges()
            let response = Music.StartPlayOrDownload.Response(musicItem: itemsArray[indexOfItemForPlay],
                                                              atIndex: indexOfItemForPlay)
            presenter?.unnewMusicItem(response: response)
        }

        playWorker = PlayMusicWorker()
        guard playWorker?.playSongByURL(url: fileUrl) ?? false else {return}
        playWorker?.delegate = self
    }
    
    func updatePlayingSongInfo(request: Music.UpdatePlayingSongInfo.Request) {
        playWorker?.callDelegateWithUpdatedInfoIfPossible()
    }
    
    private func saveChanges() {
        CoreManager.shared.saveContext()
    }
}

extension MusicInteractor: PlayMusicWorkerDelegate {
    func didFinishPlaySong() {
        
    }
    
    func updatedPlayingStateAndInfo(playingInfo: Music.UpdatePlayingSongInfo.SongInfoForDisplay) {
        var response = Music.UpdatePlayingSongInfo.Response(info: playingInfo)
        response.info.title = itemsArray[indexOfItemForPlay].displayFileName
        presenter?.updatePlayingSongInfo(response: response)
    }
}
