//
//  MusicInteractor.swift
//  VideoPlayer
//
//  Created by Sergey Pohrebnuak on 13.01.2021.
//  Copyright (c) 2021 Sergey Pohrebnuak. All rights reserved.
//
//  This file was generated by the Clean Swift Xcode Templates so
//  you can apply clean architecture to your iOS and Mac projects,
//  see http://clean-swift.com
//

import UIKit

protocol MusicBusinessLogic {
    func fetchLocalItems(request: Music.FetchLocalItems.Request)
    func startPlay(atIndex index: Int)
}

protocol MusicDataStore {
    var itemsSet: Set<MusicOrVideoItem> {get}
}

class MusicInteractor: MusicBusinessLogic, MusicDataStore {
    
    var presenter: MusicPresentationLogic?
    var worker: FetchFromLocalStorageWorker?
    
    private(set) var itemsSet = Set<MusicOrVideoItem>()
    private(set) var itemsArray = [MusicOrVideoItem]()
    
    private let musicExtension = ".mp3"
    
    // MARK: Do something
    func fetchLocalItems(request: Music.FetchLocalItems.Request) {
        worker = FetchFromLocalStorageWorker()
        worker?.fetch(byTypeExtension: musicExtension)
        
        itemsSet = CoreManager.shared.getMediaItems()
        itemsArray = Array(itemsSet)
        
        let response = Music.FetchLocalItems.Response(musicItems: itemsArray)
        presenter?.showMusicItems(response: response)
    }
    
    func startPlay(atIndex index: Int) {
        
    }
}
